config/routes.rb
Rails.application.routes.draw do
  root to: "concerns#top"
  resources :concerns do
    collection do
      post :confirm
    end
    resources :comments do
      resources :likes, only: [:create, :destroy, :edit, :update]
    end
  end

  resources :conversations do
    resources :messages
  end

  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :sessions, only:[:new, :create, :destroy]
  resources :favorites, only:[:create, :destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :concern
  belongs_to :user
  has_many :likes, dependent: :destroy

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login, only: [:create, :edit, :update, :destroy]
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_action :ensure_correct_poster, only: [:edit, :destroy]
  before_action :set_concern_comment, only: [:create, :edit, :update]

  def create
    @comment = current_user.post_comment(@concern, params[:comment])
    @likes = Like.where(comment_id: params[:id])
    if @comment.save
      render :show
    else
      render json: @comment.errors, status: 422
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to concern_path(@concern.id), notice:"編集しました"
    else
      render :edit
    end
  end

  def destroy
    @concern = Concern.find(params[:concern_id])
    @comment.destroy
    redirect_to concern_path(@concern.id), notice:"削除しました"
  end

  private

  def comment_params
    params.require(:comment).permit(:concern_id, :content)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def ensure_correct_poster
    redirect_to concerns_path(@concern) unless @comment.user_id == current_user.id
  end

  def set_concern_comment
    @concern = Concern.find(params[:concern_id])
  end

end

app/views/comments/_form.html.erb
<%= form_with(model: [concern, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :コメント %>
    <%= form.text_area :content, id: "comment_area", :class => "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "投稿", :id => "comment_submit", :class => "btn btn-default" %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul class="comment_index">
  <% comments.each do |comment| %>
    <div class="comment_area">
      <% if comment.id.present? %>
        <li>
          <div class="comment_icon_area">
            <p class="user_icon"><%= image_tag(comment.user.icon.url, class: "comment_icon" ) if comment.user.icon.url.present? %></p>
            <p><%= comment.content %></p>
          </div>
          <p class="posted_by_at">posted by <%=link_to comment.user.name, conversations_path(sender_id: current_user.id, recipient_id: comment.user.id), method: :post %></p>
          <p class="posted_by_at"><%= comment.created_at.strftime("%Y-%m-%d %H:%M:%S") %></p>
        </li>
        <% if logged_in? %>
          <% if comment.user_id == current_user.id %>
            <%= link_to edit_concern_comment_path(concern.id,comment.id) do %>
              <i class="fa fa-pencil-square-o" aria-hidden="true"></i>編集
            <% end %>
            <%= link_to concern_comment_path(concern.id,comment.id), method: :delete, data: { confirm: "本当に削除していいですか？" }  do %>
              <i class="fa fa-trash-o" aria-hidden="true"></i>削除
            <% end %>
          <% end %>
        <% end %>
        <div id="like-button_<%=comment.id %>">
          <%= render "likes/like", comment: comment %>
        </div>
      </div>
    <% end %>
  <% end %>
</ul>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/edit.html.erb
<%= form_with(model: [@concern, @comment], local: true) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h4><%= "必要事項を入力してください" %></h4>
      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>