config/routes.rb
Rails.application.routes.draw do
  root to: "concerns#top"
  resources :concerns do
    collection do
      post :confirm
    end
    resources :comments do
      resources :likes, only: [:create, :destroy, :edit, :update]
    end
  end

  resources :conversations do
    resources :messages
  end

  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :sessions, only:[:new, :create, :destroy]
  resources :favorites, only:[:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true
  validates :password, presence: true, length:{minimum:6}
  has_many :favorite_concerns, through: :favorite, source: :concern, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :concerns, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_secure_password
  mount_uploader :icon, IconUploader

  def post_comment(concern, content)
    comment = comments.build(content: content)
    comment.concern_id = concern.id
    comment
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :ensure_correct_user, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to concerns_path(session[:user_id]), notice: "登録しました！"
    else
      render :new
    end
  end

  def show
    @concerns = @user.favorites
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path, notice: "更新しました"
    else
      render :edit
    end
  end

    private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :icon)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def ensure_correct_user
      redirect_to concerns_path unless @user.id == current_user.id
    end
end

app/views/users/_form.html.erb
<div class="row form sing_up">
  <div class="col-md-6 col-md-offset-3">
    <h2>Sign up</h2>
    <%= form_with(model: @user, local: true) do |form| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h4>必要事項を入力してください</h4>
          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :email %>
        <%= form.email_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.file_field :icon %>
      </div>
      <%= form.submit 'アカウントを作成する', class: 'btn btn-danger btn-block' %>
    <% end %>
    <p>アカウントをお持ちですか？ <%= link_to "Log in", new_session_path %></p>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<div class="list_and_new_btn">
  <div class="back_to_list">
    <%= link_to concerns_path do %>
      <i class="fa fa-chevron-left fa-lg fa-fw" aria-hidden="true"></i><span>一覧へ</span>
    <% end %>
  </div>
  <div class="back_to_list">
    <%= link_to new_concern_path do %>
    <i class="fa fa-plus-square fa-lg fa-fw" aria-hidden="true"></i><span>新規投稿</span>
    <% end %>
  </div>
</div>
<div class="container_fluid">
  <div class="row">
    <div class="user_page col-xs-11 col-sm-6 col-md-3">
      <h3><%= @user.name %>のページ</h3>
      <p>メールアドレス：<%= @user.email %></p>
      <p><%= link_to "アカウントを編集する", edit_user_path(@user) %></p>
    </div>
    <div class="user_icon col-xs-11 col-sm-6 col-md-3">
      <%= image_tag(@user.icon.url, class: "icon_area" ) if @user.icon.url.present? %>
    </div>
  </div>
<div>

<div class="concern_index_area">
  <% @concerns.each do |concern| %>
  <div class="concern_index">
    <p>投稿：<%=link_to concern.concern.user.name, conversations_path(sender_id: current_user.id, recipient_id: concern.concern.user.id), method: :post %></p>
    <p>タイトル：<%= concern.concern.title %></p>
    <p>内容：<%= truncate(concern.concern.content,length: 50) %></p>
    <%= link_to concern_path(concern.concern.id) do %>
      <i class="fa fa-commenting" aria-hidden="true"></i>続きを読む
    <% end %>
    <%= link_to favorite_path(id: concern.id), method: :delete do %>
      <i class="fa fa-heart" aria-hidden="true"></i>お気に入り解除
    <% end %>
  </div>
    <% end %>
</div>