config/routes.rb
Rails.application.routes.draw do
  root to: "concerns#top"
  resources :concerns do
    collection do
      post :confirm
    end
    resources :comments do
      resources :likes, only: [:create, :destroy, :edit, :update]
    end
  end

  resources :conversations do
    resources :messages
  end

  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :sessions, only:[:new, :create, :destroy]
  resources :favorites, only:[:create, :destroy]
end

app/models/concern.rb
class Concern < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user, dependent: :destroy
  has_many :comments, dependent: :destroy

  mount_uploader :image, ImageUploader
end

app/controllers/concerns_controller.rb
class ConcernsController < ApplicationController
  before_action :require_login, only: [:new, :edit, :destroy]
  before_action :set_concern, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:destroy, :edit]

  def index
    @search = Concern.ransack(params[:q])
    @concerns = @search.result.order('created_at DESC')
  end

  def new
    if params[:back]
      @concern = Concern.new(concern_params)
    else
      @concern = Concern.new
    end
  end

  def create
    @concern = current_user.concerns.build(concern_params)
    if @concern.save
      redirect_to concerns_path, notice: '投稿されました。'
    else
      render :new
    end
  end

  def edit
  end

  def show
    @search = Concern.ransack(params[:q])
    @concerns = @search.result
    @comments = @concern.comments.all.order('created_at DESC')
    @comment = @concern.comments.build
    @favorite = current_user.favorites.find_by(concern_id: @concern.id) if logged_in?
  end

  def update
    if @concern.update(concern_params)
      redirect_to concerns_path, notice: '投稿を編集しました。'
    else
      render :edit
    end
  end

  def destroy
    @concern.destroy
    redirect_to concerns_path, notice: '投稿を削除しました。'
  end

  def confirm
    @concern = current_user.concerns.build(concern_params)
    render :new if @concern.invalid?
  end

  private

  def concern_params
    params.require(:concern).permit(:title, :content, :image, :image_cache)
  end

  def set_concern
    @concern = Concern.find(params[:id])
  end

  def set_user
    redirect_to concerns_path unless @concern.user_id == current_user.id
  end
end

app/helpers/concerns_helper.rb
module ConcernsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_concerns_path
    elsif action_name == 'edit'
      concern_path
    end
  end
end

app/views/concerns/_form.html.erb
<%= form_with(model: @concern, local: true, url: choose_new_or_edit) do |form| %>
  <% if @concern.errors.any? %>
    <div id="error_explanation">
      <h2><%= @concern.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @concern.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="concern_form">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control" %>
    <%= form.label :image %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
    <%= form.submit :class => "search_button" %>
  </div>
<% end %>

app/views/concerns/confirm.html.erb
<div class="confirm_form">
  <h4>以下の内容で投稿します。</h4>
  <%= form_with(model: @concern, url: concerns_path, local: true) do |form| %>
    <section class="card">
      <%= image_tag(@concern.image.url) if @concern.image.url.present? %>
      <%= form.hidden_field :image_cache %><br>
      <div class="card-content">
        <%= form.hidden_field :title %>
        <%= form.hidden_field :content %>
        <p class="card-title">タイトル：<%= @concern.title %></p>
        <p class="card-text">内容：<%= @concern.content %></p>
      </div>
    <%=form.submit '投稿', class: "square_btn" %>
  <% end %>

  <%= form_with(model: @concern, url: new_concern_path, local: true, method: "get") do |form| %>
    <%= form.hidden_field :title %>
    <%= form.hidden_field :content %>
    <%= form.hidden_field :image_cache if @concern.image.url %>
    <%= form.submit "戻る", name: "back", class: "btn btn-warning" %>
  <% end %>
   </section>
</div>

app/views/concerns/edit.html.erb
<%= render 'form' %>

app/views/concerns/index.html.erb
<div class="index_container">
  <div class="index_img">
    <%=image_tag "concern_index_img.jpg", :class => "concern_index_img" %>
  </div>
  <div class="search">
    <%= search_form_for @search do |search| %>
      <%= search.label :title_cont, "内容検索" %>
      <%= search.search_field :title_or_content_cont_any, class: "search_area", placeholder: "search.." %>
      <%= search.button fa_icon("search"), class: "btn btn-default btn-lg" %>
    <% end %>
  </div>
</div>
<div class="list_and_new_btn">
  <div class="back_to_list">
    <%= link_to new_concern_path do %>
    <i class="fa fa-plus-square fa-lg fa-fw" aria-hidden="true"></i><span>新規投稿</span>
    <% end %>
  </div>
  <div class="back_to_list">
    <%= link_to user_path(current_user.id) do %>
      <i class="fa fa-smile-o fa-lg fa-fw" aria-hidden="true"></i><span>Your Account</span>
    <% end %>
  </div>
</div>
<p><%= notice %></p>
<div class="concern_index_area">
  <% @concerns.each do |concern| %>
  <div class="concern_index">
    <p>投稿：<%=link_to concern.user.name, conversations_path(sender_id: current_user.id, recipient_id: concern.user.id), method: :post %></p>
    <p>タイトル：<%= concern.title %></p>
    <p>内容：<%= truncate(concern.content,length: 50) %></p>
    <%= link_to concern_path(concern.id) do %>
      <i class="fa fa-commenting" aria-hidden="true"></i>続きを読む
    <% end %>
    <% if logged_in? %>
      <% if concern.user_id == current_user.id %>
        <%= link_to edit_concern_path(concern.id) do %>
          <i class="fa fa-pencil-square-o" aria-hidden="true"></i>編集
        <% end %>
        <%= link_to concern_path(concern.id), method: :delete, data: { confirm: "本当に削除しますか?"} do %>
          <i class="fa fa-trash-o" aria-hidden="true"></i>削除
        <% end %>
      <% end %>
  </div>
    <% end %>
  <% end %>
</div>

<div id="page_top"><a href="#"></a></div>

app/views/concerns/new.html.erb
<%= render 'form' %>

app/views/concerns/show.html.erb
<div class="list_and_new_btn">
  <div class="back_to_list">
    <%= link_to concerns_path do %>
      <i class="fa fa-chevron-left fa-lg fa-fw" aria-hidden="true"></i><span>一覧へ</span>
    <% end %>
  </div>
  <div class="back_to_list">
    <%= link_to new_concern_path do %>
    <i class="fa fa-plus-square fa-lg fa-fw" aria-hidden="true"></i><span>新規投稿</span>
    <% end %>
  </div>
  <div class="back_to_list">
    <%= link_to user_path(current_user.id) do %>
      <i class="fa fa-smile-o fa-lg fa-fw" aria-hidden="true"></i><span>Your Account</span>
    <% end %>
  </div>
</div>

<dl class="search_in_show">
    <%= search_form_for @search do |form| %>
      <%= form.label :title_cont, "内容検索" %>
      <%= form.search_field :title_or_content_cont_any, class: "search_area_in_show", placeholder: "search.." %>
      <%= form.button fa_icon("search"), class: "btn btn-default btn-md" %>
    <% end %>
</dl>

<div class="container">
  <p class="box"><%= @concern.user.name %>'s icon：<%= image_tag(@concern.user.icon.url, class: "comment_icon" ) if @concern.user.icon.url.present? %></p>
  <p class="box">投稿：<%=link_to @concern.user.name, conversations_path(sender_id: current_user.id, recipient_id: @concern.user.id), method: :post %></p>
  <p class="box">タイトル： <%= @concern.title %></p>
  <div class="note">
    <p class="line_break"><%= @concern.content %></p>
    <p><%= image_tag(@concern.image.url, class: "show_image") if @concern.image.url.present? %></p>
    <% if logged_in? %>
      <% if @concern.user_id == current_user.id %>
        <%= link_to edit_concern_path(@concern) do %>
          <i class="fa fa-pencil-square-o" aria-hidden="true"></i>編集
        <% end %>
        <%= link_to concern_path(@concern.id), method: :delete, data: { confirm: "本当に削除しますか?"} do %>
          <i class="fa fa-trash-o" aria-hidden="true"></i>削除
        <% end %>
      <% end %>
      <% unless @concern.user == current_user %>
        <% if @favorite.present? %>
          <%= link_to favorite_path(id:@favorite.id), method: :delete do %>
            <i class="fa fa-heart" aria-hidden="true"></i>お気に入り解除
          <% end %>
        <% else %>
          <%= link_to favorites_path(picture_id:@concern.id), method: :post do %>
            <i class="fa fa-heart-o" aria-hidden="true"></i>お気に入り
          <% end %>
        <% end %>
      <% end %>
    </div>
    <% end %>

  <p>コメント一覧</p>
  <div>
    <%= render partial: "comments/form", locals: {comment: @comment, concern: @concern} %>
  </div>
  <div id="comments_area">
    <%= render partial: "comments/index", locals: {comments: @comments, concern: @concern} %>
  </div>

  <div id="page_top"><a href="#"></a></div>

app/views/concerns/top.html.erb
<section class="main-image container">
  <%= image_tag "top.jpg", class: "top_image" %>
  <p class="title">get the way YOU THINK</p>
  <% if logged_in? %>
    <%= link_to concerns_path do %>
      <p class="top_icon"><i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i>start</p>
    <% end %>
  <% else %>
    <%= link_to new_user_path do %>
      <p class="top_icon"><i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i>sign up</p>
    <% end %>
  <% end %>
</section>
<div class="top message1">
  <p>About get the way YOU THINK</p>
  <p>壁にぶち当たった時、友達に相談しても家族に相談しても気持ちが晴れず、誰かにこの壁を壊してもらいたいと思ったことはありませんか？</p>
</div>

<div class="top message2 color">
  <p>キーワードで検索することができます。</p>
  <p>一番解決したい言葉を入力してください。</p>
</div>

<div class="top message3">
  <p>他ユーザーから、問題を解決するためのヒントが、コメントとして投稿されます。</p>
</div>

<div class="top message4 color">
  <p>他のユーザーのお名前をクリックすると、直接メッセージを送り合うことができます。</p>
</div>

<div class="message5">
  <p>すべての人が自分らしく生きる未来へ</p>
  <p>get the way YOU THINKがお役に立てれば幸いです。</p>
</div>

<div class="footer fadein">
  <a>利用規約</a> / <a>プライバシーポリシー</a>
</div>

<div id="page_top"><a href="#"></a></div>