config/routes.rb
Rails.application.routes.draw do
  root to: "concerns#top"
  resources :concerns do
    collection do
      post :confirm
    end
    resources :comments do
      resources :likes, only: [:create, :destroy, :edit, :update]
    end
  end

  resources :conversations do
    resources :messages
  end

  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :sessions, only:[:new, :create, :destroy]
  resources :favorites, only:[:create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>get the way YOU THINK</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <meta name="viewport" content="width=device-width">
   </head>
   <body>
      <header>
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
                <span class="sr-only">get the way YOU THINK</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">get the way YOU THINK</a>
            </div>
            <div id="gnavi" class="collapse navbar-collapse">
              <ul class="nav navbar-nav navbar-right">
                <% if logged_in? %>
                  <li><%= link_to "Log out", session_path(current_user.id), method: :delete %></li>
                <% else %>
                  <li><%= link_to "Sign up", new_user_path %></li>
                  <li><%= link_to "Log in", new_session_path %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </header>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>